export type Food = {
  id: string;
  name: string;
  water: number;      // ml per 100g
  sodium: number;     // mg per 100g
  potassium: number;  // mg per 100g
  phosphorus: number; // mg per 100g
};

// Values are approximate per 100g (cooked/as-served unless noted)
export const FOODS: Food[] = [
  // ── 主食・麺 ──────────────────────────────────────────
  { id: "rice",          name: "白米",          water: 60,  sodium:   1, potassium:  29, phosphorus:  34 },
  { id: "brown_rice",    name: "玄米",          water: 60,  sodium:   1, potassium:  95, phosphorus: 130 },
  { id: "fried_rice",    name: "チャーハン",    water: 55,  sodium: 350, potassium:  70, phosphorus:  60 },
  { id: "curry_rice",    name: "カレーライス",  water: 65,  sodium: 400, potassium: 120, phosphorus:  50 },
  { id: "bread",         name: "食パン",        water: 38,  sodium: 500, potassium:  97, phosphorus:  85 },
  { id: "udon",          name: "うどん",        water: 75,  sodium: 200, potassium:  20, phosphorus:  18 },
  { id: "soba",          name: "そば",          water: 68,  sodium:  60, potassium: 100, phosphorus:  95 },
  { id: "ramen",         name: "ラーメン",      water: 88,  sodium: 800, potassium: 100, phosphorus:  50 },
  { id: "spaghetti",     name: "スパゲティ",    water: 65,  sodium:   1, potassium:  55, phosphorus:  90 },
  { id: "onigiri",       name: "おにぎり",      water: 56,  sodium: 220, potassium:  29, phosphorus:  40 },
  { id: "yakisoba",      name: "焼きそば",      water: 60,  sodium: 500, potassium:  80, phosphorus:  55 },
  { id: "okonomiyaki",   name: "お好み焼き",    water: 62,  sodium: 450, potassium: 120, phosphorus:  90 },
  { id: "gyoza_fried",   name: "焼き餃子",      water: 55,  sodium: 500, potassium: 150, phosphorus:  90 },
  { id: "pizza",         name: "ピザ",          water: 45,  sodium: 550, potassium: 120, phosphorus: 130 },
  { id: "rice_porridge", name: "お粥",          water: 84,  sodium:   1, potassium:  14, phosphorus:  17 },
  { id: "zosui",         name: "雑炊",          water: 86,  sodium: 300, potassium:  50, phosphorus:  25 },
  { id: "croissant",     name: "クロワッサン",  water: 20,  sodium: 500, potassium:  80, phosphorus: 100 },
  { id: "pancake",       name: "ホットケーキ",  water: 40,  sodium: 340, potassium: 100, phosphorus: 130 },

  // ── 汁物 ──────────────────────────────────────────────
  { id: "miso_soup",     name: "みそ汁",        water: 93,  sodium: 600, potassium:  80, phosphorus:  40 },
  { id: "consomme",      name: "コンソメスープ",water: 94,  sodium: 500, potassium: 100, phosphorus:  20 },
  { id: "chinese_soup",  name: "中華スープ",    water: 93,  sodium: 550, potassium:  90, phosphorus:  20 },
  { id: "potage",        name: "ポタージュ",    water: 88,  sodium: 400, potassium: 180, phosphorus:  60 },
  { id: "curry_liquid",  name: "カレー（汁）",  water: 80,  sodium: 500, potassium: 150, phosphorus:  50 },
  { id: "stew",          name: "シチュー",      water: 82,  sodium: 450, potassium: 200, phosphorus:  60 },
  { id: "tonjiru",       name: "豚汁",          water: 90,  sodium: 550, potassium: 130, phosphorus:  50 },
  { id: "nabe",          name: "鍋（水炊き）",  water: 92,  sodium: 350, potassium: 150, phosphorus:  60 },
  { id: "corn_potage",   name: "コーンポタージュ",water: 88, sodium: 400, potassium: 160, phosphorus:  55 },
  { id: "tomato_soup",   name: "トマトスープ",  water: 91,  sodium: 450, potassium: 220, phosphorus:  30 },

  // ── 飲み物 ────────────────────────────────────────────
  { id: "water_drink",   name: "水",            water: 100, sodium:   0, potassium:   0, phosphorus:   0 },
  { id: "green_tea",     name: "お茶（緑茶）",  water: 100, sodium:   0, potassium:  27, phosphorus:   2 },
  { id: "coffee",        name: "コーヒー",      water:  99, sodium:   1, potassium:  65, phosphorus:   7 },
  { id: "beer",          name: "アルコール（ビール）",water: 93, sodium: 4, potassium: 34, phosphorus:  15 },
  { id: "orange_juice",  name: "オレンジジュース",water: 89, sodium:  1, potassium: 200, phosphorus:  13 },
  { id: "sports_drink",  name: "スポーツドリンク",water: 94, sodium: 49, potassium:  20, phosphorus:   4 },
  { id: "cola",          name: "コーラ",        water: 89,  sodium:   4, potassium:   2, phosphorus:  12 },
  { id: "soy_milk",      name: "豆乳（無調整）",water: 91,  sodium:  51, potassium: 190, phosphorus:  44 },
  { id: "barley_tea",    name: "麦茶",          water: 100, sodium:   1, potassium:   6, phosphorus:   2 },
  { id: "vegetable_juice",name: "野菜ジュース", water: 94,  sodium: 120, potassium: 250, phosphorus:  15 },
  { id: "black_tea",     name: "紅茶",          water: 100, sodium:   1, potassium:  8, phosphorus:   2 },
  { id: "milk_latte",    name: "カフェラテ",    water: 89,  sodium:  50, potassium: 150, phosphorus:  90 },

  // ── 肉類 ──────────────────────────────────────────────
  { id: "chicken_b",     name: "鶏むね肉",      water: 74,  sodium:  60, potassium: 330, phosphorus: 220 },
  { id: "chicken_t",     name: "鶏もも肉",      water: 72,  sodium:  70, potassium: 290, phosphorus: 200 },
  { id: "sasami",        name: "鶏ささみ",      water: 75,  sodium:  40, potassium: 320, phosphorus: 210 },
  { id: "pork_loin",     name: "豚ロース",      water: 63,  sodium:  60, potassium: 290, phosphorus: 200 },
  { id: "pork_belly",    name: "豚バラ",        water: 49,  sodium:  50, potassium: 230, phosphorus: 130 },
  { id: "beef",          name: "牛もも肉",      water: 68,  sodium:  60, potassium: 290, phosphorus: 175 },
  { id: "beef_belly",    name: "牛バラ",        water: 54,  sodium:  55, potassium: 230, phosphorus: 130 },
  { id: "minced",        name: "ひき肉（合い挽き）",water: 61, sodium: 70, potassium: 280, phosphorus: 160 },
  { id: "liver_chicken", name: "鶏レバー",      water: 75,  sodium:  85, potassium: 330, phosphorus: 300 },
  { id: "liver_pork",    name: "豚レバー",      water: 71,  sodium:  55, potassium: 290, phosphorus: 340 },
  { id: "lamb",          name: "ラム肉",        water: 68,  sodium:  70, potassium: 280, phosphorus: 160 },
  { id: "chicken_wing",  name: "手羽元",        water: 68,  sodium:  85, potassium: 250, phosphorus: 160 },
  { id: "duck",          name: "鴨肉",          water: 65,  sodium:  67, potassium: 280, phosphorus: 170 },
  { id: "pork_shoulder", name: "豚肩ロース",    water: 64,  sodium:  65, potassium: 310, phosphorus: 195 },

  // ── 魚類 ──────────────────────────────────────────────
  { id: "salmon",        name: "さけ（生）",    water: 72,  sodium:  66, potassium: 350, phosphorus: 240 },
  { id: "salmon_salt",   name: "塩さけ",        water: 65,  sodium: 700, potassium: 320, phosphorus: 230 },
  { id: "mackerel",      name: "さば",          water: 62,  sodium: 110, potassium: 330, phosphorus: 220 },
  { id: "aji",           name: "あじ",          water: 75,  sodium: 120, potassium: 320, phosphorus: 200 },
  { id: "iwashi",        name: "いわし",        water: 67,  sodium: 150, potassium: 290, phosphorus: 230 },
  { id: "tuna",          name: "まぐろ",        water: 70,  sodium:  43, potassium: 380, phosphorus: 270 },
  { id: "buri",          name: "ぶり",          water: 59,  sodium:  65, potassium: 380, phosphorus: 130 },
  { id: "tai",           name: "たい",          water: 75,  sodium:  55, potassium: 340, phosphorus: 220 },
  { id: "shrimp",        name: "えび",          water: 79,  sodium: 170, potassium: 230, phosphorus: 200 },
  { id: "cod",           name: "たら",          water: 81,  sodium: 110, potassium: 350, phosphorus: 230 },
  { id: "squid",         name: "いか",          water: 80,  sodium: 200, potassium: 290, phosphorus: 250 },
  { id: "octopus",       name: "たこ",          water: 81,  sodium: 280, potassium: 290, phosphorus: 160 },
  { id: "oyster",        name: "かき（牡蠣）",  water: 85,  sodium: 520, potassium: 190, phosphorus: 100 },
  { id: "scallop",       name: "ほたて",        water: 83,  sodium: 120, potassium: 310, phosphorus: 160 },
  { id: "canned_mackerel",name: "さば缶（水煮）",water: 70, sodium: 470, potassium: 270, phosphorus: 230 },
  { id: "dried_fish",    name: "ひもの（あじ）",water: 50,  sodium: 1200,potassium: 350, phosphorus: 250 },
  { id: "flatfish",      name: "ひらめ",        water: 77,  sodium:  95, potassium: 440, phosphorus: 230 },

  // ── 卵・豆腐・豆類 ────────────────────────────────────
  { id: "egg",           name: "卵",            water: 76,  sodium: 140, potassium: 130, phosphorus: 180 },
  { id: "tofu_m",        name: "豆腐（木綿）",  water: 87,  sodium:   5, potassium: 110, phosphorus: 110 },
  { id: "tofu_k",        name: "絹豆腐",        water: 89,  sodium:   5, potassium: 140, phosphorus:  88 },
  { id: "natto",         name: "納豆",          water: 60,  sodium:   2, potassium: 660, phosphorus: 190 },
  { id: "abura_age",     name: "油揚げ",        water: 39,  sodium:   1, potassium: 150, phosphorus: 170 },
  { id: "atsuage",       name: "厚揚げ",        water: 63,  sodium:   5, potassium: 120, phosphorus: 150 },
  { id: "ganmodoki",     name: "がんもどき",    water: 64,  sodium:   1, potassium: 140, phosphorus: 180 },
  { id: "edamame",       name: "枝豆",          water: 72,  sodium:   1, potassium: 490, phosphorus: 170 },
  { id: "soy_beans",     name: "大豆（ゆで）",  water: 66,  sodium:   1, potassium: 530, phosphorus: 190 },

  // ── 野菜 ──────────────────────────────────────────────
  { id: "cabbage",       name: "キャベツ",      water: 93,  sodium:   5, potassium: 200, phosphorus:  27 },
  { id: "cucumber",      name: "きゅうり",      water: 95,  sodium:   1, potassium: 200, phosphorus:  36 },
  { id: "tomato",        name: "トマト",        water: 94,  sodium:   7, potassium: 210, phosphorus:  26 },
  { id: "broccoli",      name: "ブロッコリー",  water: 89,  sodium:  14, potassium: 360, phosphorus:  89 },
  { id: "lettuce",       name: "レタス",        water: 96,  sodium:   4, potassium: 200, phosphorus:  22 },
  { id: "moyashi",       name: "もやし",        water: 95,  sodium:   2, potassium:  69, phosphorus:  51 },
  { id: "eggplant",      name: "なす",          water: 93,  sodium:   0, potassium: 220, phosphorus:  30 },
  { id: "green_pepper",  name: "ピーマン",      water: 93,  sodium:   1, potassium: 190, phosphorus:  22 },
  { id: "daikon",        name: "大根",          water: 95,  sodium:  16, potassium: 230, phosphorus:  18 },
  { id: "onion",         name: "玉ねぎ",        water: 90,  sodium:   2, potassium: 150, phosphorus:  31 },
  { id: "shiitake",      name: "しいたけ",      water: 91,  sodium:   2, potassium: 290, phosphorus:  57 },
  { id: "enoki",         name: "えのき",        water: 88,  sodium:   2, potassium: 340, phosphorus:  96 },
  { id: "komatsuna",     name: "小松菜",        water: 95,  sodium:  15, potassium: 500, phosphorus:  45 },
  { id: "corn",          name: "とうもろこし",  water: 77,  sodium:   1, potassium: 290, phosphorus: 100 },
  { id: "carrot",        name: "にんじん",      water: 89,  sodium:  30, potassium: 270, phosphorus:  26 },
  { id: "pumpkin",       name: "かぼちゃ",      water: 87,  sodium:   1, potassium: 450, phosphorus:  43 },
  { id: "potato",        name: "じゃがいも",    water: 81,  sodium:   1, potassium: 410, phosphorus:  47 },
  { id: "spinach",       name: "ほうれん草",    water: 92,  sodium:  16, potassium: 690, phosphorus:  47 },
  { id: "sweet_potato",  name: "さつまいも",    water: 66,  sodium:   1, potassium: 480, phosphorus:  47 },
  { id: "asparagus",     name: "アスパラガス",  water: 92,  sodium:   2, potassium: 270, phosphorus:  60 },
  { id: "chinese_cabbage",name: "白菜",         water: 95,  sodium:   6, potassium: 220, phosphorus:  33 },
  { id: "celery",        name: "セロリ",        water: 95,  sodium:  28, potassium: 410, phosphorus:  39 },
  { id: "burdock",       name: "ごぼう",        water: 81,  sodium:  18, potassium: 320, phosphorus:  62 },
  { id: "lotus_root",    name: "れんこん",      water: 81,  sodium:  24, potassium: 440, phosphorus:  74 },
  { id: "chives",        name: "にら",          water: 92,  sodium:   1, potassium: 510, phosphorus:  45 },
  { id: "bamboo_shoot",  name: "たけのこ",      water: 89,  sodium:   1, potassium: 520, phosphorus:  62 },
  { id: "okra",          name: "オクラ",        water: 90,  sodium:   4, potassium: 260, phosphorus:  58 },
  { id: "green_beans",   name: "いんげん",      water: 91,  sodium:   1, potassium: 260, phosphorus:  41 },
  { id: "shungiku",      name: "春菊",          water: 91,  sodium:  73, potassium: 460, phosphorus:  44 },
  { id: "taro",          name: "里いも",        water: 84,  sodium:   1, potassium: 640, phosphorus:  55 },

  // ── 果物 ──────────────────────────────────────────────
  { id: "apple",         name: "りんご",        water: 84,  sodium:   0, potassium: 120, phosphorus:  12 },
  { id: "mikan",         name: "みかん",        water: 87,  sodium:   1, potassium: 150, phosphorus:  15 },
  { id: "pear",          name: "なし",          water: 88,  sodium:   0, potassium: 140, phosphorus:  11 },
  { id: "peach",         name: "もも",          water: 88,  sodium:   0, potassium: 180, phosphorus:  18 },
  { id: "watermelon",    name: "すいか",        water: 90,  sodium:   1, potassium: 120, phosphorus:   8 },
  { id: "strawberry",    name: "いちご",        water: 90,  sodium:   0, potassium: 170, phosphorus:  31 },
  { id: "grape",         name: "ぶどう",        water: 83,  sodium:   1, potassium: 130, phosphorus:  15 },
  { id: "banana",        name: "バナナ",        water: 75,  sodium:   0, potassium: 360, phosphorus:  27 },
  { id: "kiwi",          name: "キウイ",        water: 84,  sodium:   2, potassium: 300, phosphorus:  32 },
  { id: "melon",         name: "メロン",        water: 87,  sodium:   7, potassium: 350, phosphorus:  14 },
  { id: "pineapple",     name: "パイナップル",  water: 86,  sodium:   0, potassium: 150, phosphorus:   9 },
  { id: "mango",         name: "マンゴー",      water: 82,  sodium:   1, potassium: 170, phosphorus:  12 },
  { id: "grapefruit",    name: "グレープフルーツ",water: 89, sodium:  1, potassium: 140, phosphorus:  17 },
  { id: "fig",           name: "いちじく",      water: 84,  sodium:   2, potassium: 170, phosphorus:  23 },
  { id: "persimmon",     name: "柿",            water: 83,  sodium:   1, potassium: 170, phosphorus:  14 },
  { id: "lemon",         name: "レモン",        water: 85,  sodium:   4, potassium: 130, phosphorus:  15 },

  // ── 調理済み ──────────────────────────────────────────
  { id: "karaage",       name: "から揚げ",      water: 54,  sodium: 400, potassium: 290, phosphorus: 230 },
  { id: "yakizakana",    name: "焼き魚",        water: 65,  sodium: 200, potassium: 320, phosphorus: 220 },
  { id: "hamburger",     name: "ハンバーグ",    water: 55,  sodium: 500, potassium: 280, phosphorus: 160 },
  { id: "tonkatsu",      name: "とんかつ",      water: 45,  sodium: 450, potassium: 280, phosphorus: 180 },
  { id: "croquette",     name: "コロッケ",      water: 52,  sodium: 420, potassium: 320, phosphorus:  90 },
  { id: "tamagoyaki",    name: "玉子焼き",      water: 72,  sodium: 350, potassium: 130, phosphorus: 160 },
  { id: "tempura_shrimp",name: "エビ天ぷら",   water: 60,  sodium: 350, potassium: 200, phosphorus: 200 },
  { id: "yakitori",      name: "焼き鳥",        water: 60,  sodium: 550, potassium: 280, phosphorus: 190 },
  { id: "niku_jaga",     name: "肉じゃが",      water: 82,  sodium: 450, potassium: 300, phosphorus: 100 },
  { id: "chawanmushi",   name: "茶碗蒸し",      water: 88,  sodium: 400, potassium: 100, phosphorus:  90 },
  { id: "gyudon",        name: "牛丼",          water: 68,  sodium: 500, potassium: 200, phosphorus: 120 },
  { id: "sushi_nigiri",  name: "にぎり寿司",    water: 65,  sodium: 250, potassium:  80, phosphorus:  80 },
  { id: "tempura_veg",   name: "野菜天ぷら",    water: 55,  sodium: 200, potassium: 250, phosphorus:  60 },
  { id: "nikujaga",      name: "煮物（根菜）",  water: 83,  sodium: 420, potassium: 320, phosphorus:  70 },
  { id: "oyakodon",      name: "親子丼",        water: 66,  sodium: 480, potassium: 180, phosphorus: 130 },
  { id: "mapo_tofu",     name: "麻婆豆腐",      water: 85,  sodium: 550, potassium: 200, phosphorus: 100 },

  // ── 加工食品 ──────────────────────────────────────────
  { id: "ham",           name: "ハム",          water: 71,  sodium: 1100,potassium: 280, phosphorus: 230 },
  { id: "wiener",        name: "ウインナー",    water: 55,  sodium: 800, potassium: 210, phosphorus: 160 },
  { id: "bacon",         name: "ベーコン",      water: 46,  sodium: 700, potassium: 270, phosphorus: 180 },
  { id: "kamaboko",      name: "かまぼこ",      water: 75,  sodium: 1000,potassium: 160, phosphorus:  90 },
  { id: "chikuwa",       name: "ちくわ",        water: 74,  sodium: 840, potassium: 110, phosphorus:  90 },
  { id: "hanpen",        name: "はんぺん",      water: 77,  sodium: 590, potassium: 160, phosphorus:  95 },
  { id: "satsuma_age",   name: "さつま揚げ",    water: 65,  sodium: 580, potassium: 110, phosphorus:  90 },
  { id: "instant_noodles",name: "インスタント麺",water: 65, sodium: 1500,potassium:  75, phosphorus:  70 },
  { id: "canned_tuna",   name: "ツナ缶（水煮）",water: 72,  sodium: 330, potassium: 230, phosphorus: 180 },
  { id: "sausage",       name: "ソーセージ",    water: 54,  sodium: 810, potassium: 200, phosphorus: 170 },

  // ── 調味料・乳製品 ────────────────────────────────────
  { id: "soy_tbsp",      name: "醤油",          water: 67,  sodium: 7000,potassium: 390, phosphorus: 170 },
  { id: "miso_tbsp",     name: "みそ",          water: 43,  sodium: 4200,potassium: 380, phosphorus: 170 },
  { id: "salt_tsp",      name: "塩",            water:  0,  sodium:39000,potassium: 100, phosphorus:   0 },
  { id: "milk",          name: "牛乳",          water: 87,  sodium:  40, potassium: 150, phosphorus:  90 },
  { id: "cheese",        name: "チーズ（プロセス）",water: 45, sodium: 800, potassium: 90, phosphorus: 630 },
  { id: "yogurt",        name: "ヨーグルト",    water: 87,  sodium:  40, potassium: 170, phosphorus: 100 },
  { id: "mayonnaise",    name: "マヨネーズ",    water: 15,  sodium: 860, potassium:  15, phosphorus:  30 },
  { id: "ketchup",       name: "ケチャップ",    water: 66,  sodium: 1200,potassium: 420, phosphorus:  40 },
  { id: "butter",        name: "バター",        water: 16,  sodium: 750, potassium:  28, phosphorus:  17 },
  { id: "dressing",      name: "ドレッシング",  water: 50,  sodium: 900, potassium:  60, phosphorus:  30 },
  { id: "worcestershire",name: "ウスターソース",water: 58,  sodium:1700, potassium: 390, phosphorus:  50 },
  { id: "cream",         name: "生クリーム",    water: 57,  sodium:  40, potassium:  90, phosphorus:  70 },
];

export function getFoodRisk(food: Food) {
  return {
    sodium:    food.sodium    > 300,
    potassium: food.potassium > 300,
  };
}
